### ISSUE TITLE
Can I share my code with *.so in peer review?

### ISSUE THREAD

**Issue by wwd29** [VIPriors/vipriors-challenges-toolkit#13]
For some reason of the privacy, my code may be not allowed to fully shared. So can I use Cython to compile some of them into *.so. I promise the results can be reproducted without violance of the rules.

**Comment by rjbruin** [comment]
I'm sorry, but we need to be able to inspect the code, to ensure the rules of the competition are followed. Therefore we require the source code of the model.

We could arrange for you to submit your code only to us, the organizers, instead of making it publicly available. Then we will not distribute it further and delete the code after the challenge concludes. Would that help?

**Comment by wwd29** [comment]
I see. Thanks for your reply.
