### ISSUE TITLE
submitting failed: no space left on device

### ISSUE THREAD

**Issue by tomeasure** [VIPriors/vipriors-challenges-toolkit#23]
Will this failed submission reduce our submission times?

```
docker: failed to register layer: Error processing tar file(exit status 1): write /opt/conda/lib/libmkl_avx512_mic.so: no space left on device.
See 'docker run --help'.
```

**Comment by rjbruin** [comment]
Hi Liu Shuai,

Codalab is having technical issues, currently. We will let you know once these are fixed.

To which competition did you submit, and with which username? Then I can check if your submission counts towards the limits.

Best regards,
Robert-Jan

________________________________
Van: Liu Shuai ***@***.***>
Verzonden: maandag 30 augustus 2021 05:17:44
Aan: VIPriors/vipriors-challenges-toolkit
CC: Subscribed
Onderwerp: [VIPriors/vipriors-challenges-toolkit] submitting failed: no space left on device (#23)


Will this failed submission reduce our submission times?

docker: failed to register layer: Error processing tar file(exit status 1): write /opt/conda/lib/libmkl_avx512_mic.so: no space left on device.
See 'docker run --help'.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_VIPriors_vipriors-2Dchallenges-2Dtoolkit_issues_23&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=KiA4rbHx0s0fo0svCzM6bPeB8Sf0p3p9TzeAXGMaF_8&m=jEWEkz_yF_axdFTVBtT07D0o2uCFE_q7LTlLxh3m0rA&s=zXX9ycdaZUKeajqy8NI_dNcurrQzTRTE-_Xc5CWPIfo&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AB4N7U7CQDMGLJ6C3KNEUBDT7LZ5RANCNFSM5DA677YA&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=KiA4rbHx0s0fo0svCzM6bPeB8Sf0p3p9TzeAXGMaF_8&m=jEWEkz_yF_axdFTVBtT07D0o2uCFE_q7LTlLxh3m0rA&s=0v3N5uNQKUoe3ipRN1WW0U7LO4vBAzmp7NqZZKz9sh4&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=KiA4rbHx0s0fo0svCzM6bPeB8Sf0p3p9TzeAXGMaF_8&m=jEWEkz_yF_axdFTVBtT07D0o2uCFE_q7LTlLxh3m0rA&s=EA5-uF12JYF4tYrAaEAd9FUC6WXi6PCqPWsVZUTOY4U&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=KiA4rbHx0s0fo0svCzM6bPeB8Sf0p3p9TzeAXGMaF_8&m=jEWEkz_yF_axdFTVBtT07D0o2uCFE_q7LTlLxh3m0rA&s=7rtedL-bwWW63gUplrvQeERolam0N-sjf897y32N3wM&e=>.

**Comment by tomeasure** [comment]
Hi Robert-Jan,

This failed submission has been removed. 
thanks.

Best regard,
Liu Shuai

**Comment by rjbruin** [comment]
The CodaLab issues appear to have been fixed, so this problem should be resolved.
