### ISSUE TITLE
no pre-training weights or additional data sets can be used

### ISSUE THREAD

**Issue by clearlove7-s11** [VIPriors/vipriors-challenges-toolkit#37]
Dear organizers, 
     Hello, I took part in the action recognition track. I see the competition policy says that no pre-training weights or additional data sets can be used. I can guarantee that I will not use it, but I cannot guarantee others. So I wonder if you have any good way to tell if the challengers are using something they shouldn't use? 
What should challengers submit in the end?
Yours
Marco

**Comment by rjbruin** [comment]
Hi Marco,

That's a good question. Competitors who wish to qualify for the final leaderboard must submit a technical report one week after the challenge deadline, so that we have some insight into how the submission was conceived. Of course, this is not entirely foolproof against cheaters. We have to rely on the integrity of competitors, especially since this is an academic challenge. For the same reason, we do not provide prizes for the winners, so as not to stimulate cheating.

**Comment by rjbruin** [comment]
As for the tech report: it can be any size report, in PDF format. We will open a submission page for these soon. The deadline is next Friday, one week after the challenge deadline closes (which is today).

**Comment by rjbruin** [comment]
For more details, please see here: https://vipriors.github.io/challenges/#report
