### ISSUE TITLE
Question about codalab website’s reopen

### ISSUE THREAD

**Issue by siyuch-fdu** [VIPriors/vipriors-challenges-toolkit#42]
Hi, organizers:
      I am gonna ask why the codalab website is open again? Is the ddl postponed? If not, is it fair for other competitors who doesn't notice this?

**Comment by Zhang-HM** [comment]
I think so, too. There's no need to restart the competition.

**Comment by jinxuan777** [comment]
I am shocked at the reason that extends the deadline. One hour ahead will not have a big impact on the final result, but 3 days will.

**Comment by LcenArthas** [comment]
I think so, I was shocked to receive an email about the temporary extend of the challenge, which showed that it was postponed to the 29th, while I've written half of the report. I don't think such a decision is fair to the current team on the leaderboard.

**Comment by jinxuan777** [comment]
We have found some wired results in detection track. Is it a chance for "cheater" to edit the results?

**Comment by jinxuan777** [comment]
It is a common sense that public score should be counted instead of private score.

**Comment by NightQing** [comment]
I'm shocked by the news that the competition reopened and delayed for more than two days. I had planned to post my report to arxiv just now and take a holiday from tomorrow.  I can't imagine what would happen if I did the above...

**Comment by rjbruin** [comment]
We are currently deliberating these issues. Please stay tuned for a short while.

**Comment by rjbruin** [comment]
> Hi, organizers:
> I am gonna ask why the codalab website is open again? Is the ddl postponed? If not, is it fair for other competitors who doesn't notice this?

An email was sent detailing why the server was reopened. If you did not receive the email you are not registered as a competitor to the competitions.

Still, please stay tuned for a comment on your issues.

**Comment by rjbruin** [comment]
Dear participants,

We have received numerous concerns about the extension of the competition deadline being unfair for most participants. After much consideration we have decided to therefore shorten the extension and to only keep the competition server open for 9 more hours, until **Sept 28, 01:59 AM UTC**. This should give enough time for those who were unable to upload their final submission to do so, yet does not allow for running extensive new experiments.

We'd like to ensure you that we do our utmost best to keep the competition as fair as possible and try to accomodate equally for all participants. We're sorry for any inconvenience and/or unclarities caused by us.

If you have any questions feel free to contact us at vipriors-ewi@tudelft.nl, yet please note that our decision is FINAL.

Best regards,
Attila Lengyel & Robert-Jan Bruintjes
